

const originCodes = [
  'ACC Aurora Coop - Chapman, NE',
  'ADA Andersons - Albion, MI',
  'ADC ADM - Columbus, NE',
  'ADE Andersons - Denison, IA',
  'ADF ADM - Fremont, NE',
  'AEL Adkins Energy - Lena, IL',
  'AEP Agri-Energy - Palestine, IL',
  'ALC AL CORN - Claremont, MN',
  'CEF Chief Ethanol Fuels - Hastings, NE',
  'CLP Corn LP - Goldfield, IA',
  'DPS Diversified Ingredients - DeWitt, IA',
  'REEA E-Energy - Adams, NE',
  'EOA Elite Octane - Atlantic, IA',
  'FHA Flint Hills - Arthur, IA',
  'FHF Flint Hills - Fairmont, NE',
  'FHM Flint Hills - Menlo, IA',
  'GEJ Guardian Energy, LLC - Janesville, MN',
  'GFE Granite Falls Energy - Granite Falls, MN',
  'GLA Glacial Lakes Energy - Aberdeen, SD',
  'GLM Glacial Lakes Energy - Mina, SD',
  'GPA Green Plains - Atkinson, NE',
  'GPF Green Plains - Fairmont, MN',
  'GPL Green Plains - Lakota, IA',
  'GPO GreenAmerica Biofuels - Ord, NE',
  'GPS Green Plains - Shenandoah, IA',
  'GPW Green Plains - Wood River, NE',
  'GPY Green Plains - York, NE',
  'HCP Heartland Corn Products - Winthrop, MN',
  'ICM ICM Biofuels - St. Joseph, MO',
  'KAA KAAPA Ethanol - Aurora, NE',
  'KAM KAAPA Ethanol - Minden, NE',
  'KAR KAAPA Ethanol - Ravenna, NE',
  'LDG Louis Dreyfus - Grand Junction, IA',
  'LDN Louis Dreyfus - Norfolk, NE',
  'LSC Little Sioux Corn Pro - Marcus, IA',
  'LWE Lincoln Way Energy - Nevada, IA',
  'NGM NuGen Energy - Marion, SD',
  'PAE Pacific Ethanol (East) - Aurora, NE',
  'PAW Pacific Ethanol (West) - Aurora, NE',
  'PBG Prairie Horizon Agri-Energy - Phillipsburg, KS',
  'PEM Plymouth Energy - Merrill, IA',
  'PLC Pine Lake Corn Processors - Steamboat Rock, IA',
  'PNA Poet Nutrition - Arthur, IA',
  'PNC Poet Nutrition - Chancellor, SD',
  'PNF Poet Nutrition - Fairmont, NE',
  'PNH Poet Nutrition - Hudson, SD',
  'PNI Poet Nutrition - Menlo, IA',
  'PNL Poet Nutrition - Mitchell, SD',
  'PNM Poet Nutrition - Macon, MO',
  'PNR Poet Nutrition - Coon Rapids, IA',
  'PNS Poet Nutrition - Scotland, SD',
  'QCP Quad County Corn Processors - Galva, IA',
  'RED Redfield Energy - Redfield, SD',
  'RNE Ringneck Energy - Onida, SD',
  'SEJ Siouxland Ethanol - Jackson, NE',
  'SIR SW IA Renewable Energy - Council Bluffs, IA',
  'TEST - Test Product',
  'TEXTURE ANALYZER',
  'UNI Univar - Omaha, NE',
  'VAC Valero - Albert City, IA',
  'VAF Valero - Fort Dodge, IA',
  'VAK Valero - Lakota, IA',
  'VAL Valero - Albion, NE',
  'VAW Valero - Welcome, MN'
];


export default originCodes;